export { Home } from './Home'
export { Popular } from './Popular'
export { NowPlaying } from './NowPlaying'
export { TopRated } from './TopRated'
export { Show } from './Show'
export { Favorites } from './Favorites'